### ISSUE TITLE
homebridge hap-nodejs

### ISSUE THREAD

**Issue by djsmix** [paolotremadio/homebridge-simple-shelly#8]
The plugin "homebridge-simple-shelly" defines 'homebridge' and/or 'hap-nodejs' in their 'dependencies' section, meaning they carry an additional copy of homebridge and hap-nodejs. This not only wastes disk space, but also can cause major incompatibility issues and thus is considered bad practice. Please inform the developer to update their plugin!

**Comment by paolotremadio** [comment]
That's fine, it's just a notice, it doesn't really matter :)

**Comment by djsmix** [comment]
Waste of disk space?

**Comment by paolotremadio** [comment]
Feel free to raise a PR

**Comment by djsmix** [comment]
doesn't really know how to do it sorry. you can take this as a PR, or then you could leave it. :)

**Comment by paolotremadio** [comment]
I’d be more than happy to make the change but it’s not a small change and it would require retesting the plug-in. At the moment I don’t have a Shelly available to test so I’d rather leave the plug-in stable, even if a tiny wasteful :)

**Comment by djsmix** [comment]
Oh, i understand. 
Ill keep an eye for maybe an update in the future! :)
